apiVersion: v1
kind: Service
metadata:
  labels:
    app: sftp-server
  name: sftp-server
spec:
  ports:
    - name: 2222-tcp
      nodePort: 32700
      port: 2222
      protocol: TCP
      targetPort: 2222
  selector:
    deploymentconfig: sftp-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
